export default {
  type: 'orbit',
  name: 'Orbit (3D image sphere)',
  settings: [
    { id: 'label',    type: 'text', label: 'Bracketed label', default: '' },
    { id: 'headline', type: 'text', label: 'Centre headline', default: '' },
    { id: 'source',   type: 'select', label: 'Items from', options: ['projects', 'manual', 'both'], default: 'both' },
    { id: 'projectAction', type: 'select', label: 'Project items open as', options: ['popup', 'page'], default: 'popup' },
    { id: 'items',    type: 'item_list', label: 'Manual items: { image, title, meta, note, action: popup|page|url, href, tall }' },
    { id: 'startView', type: 'select', label: 'Start view', options: ['sphere', 'grid'], default: 'sphere' },
    { id: 'maxItems', type: 'range', label: 'Max items', min: 4, max: 40, step: 1, default: 28 },
    { id: 'explosion', type: 'range', label: 'Scroll explosion — max spread (× sphere radius); 0 turns it off', min: 0, max: 4, step: 0.1, default: 1.6 },
    { id: 'burst', type: 'range', label: 'Extra spread from scroll SPEED', min: 0, max: 3, step: 0.05, default: 0.3 },
    { id: 'stiffness', type: 'range', label: 'Spring stiffness', min: 30, max: 400, step: 5, default: 120 },
    { id: 'bounce', type: 'range', label: 'Damping (1 = no bounce)', min: 0.15, max: 1, step: 0.01, default: 0.87 },
    { id: 'variation', type: 'range', label: 'Per-card variation', min: 0, max: 0.8, step: 0.01, default: 0.35 },
    { id: 'stagger', type: 'range', label: 'Cascade (cards leave at different moments)', min: 0, max: 0.6, step: 0.01, default: 0.25 },
    { id: 'tumble', type: 'range', label: 'Tumble while flying', min: 0, max: 1.5, step: 0.05, default: 1.5 },
    { id: 'fade', type: 'range', label: 'Fade when far away', min: 0, max: 1, step: 0.05, default: 1 },
    { id: 'squeeze', type: 'toggle', label: 'Fast upward scroll squeezes cards inward', default: true },
    { id: 'runway', type: 'range', label: 'Scroll length after pinning (svh)', min: 0, max: 300, step: 10, default: 100 },
    { id: 'cue',      type: 'text', label: 'Interaction cue', default: 'Drag to rotate' },
  ],
};
