// Generates docs/BLOCKS.md from every src/blocks/**/schema.js.
// Run: npm run docs   (also safe to run in CI — it only writes one file)
import { readdirSync, existsSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { pathToFileURL } from 'node:url';

const root = new URL('..', import.meta.url).pathname;
const blocksDir = join(root, 'src/blocks');
const find = (dir) => readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
  const p = join(dir, e.name);
  return e.isDirectory() ? (existsSync(join(p, 'schema.js')) ? [join(p, 'schema.js')] : find(p)) : [];
});

const rows = [];
for (const file of find(blocksDir).sort()) {
  const { default: s } = await import(pathToFileURL(file).href);
  rows.push({ s, file: relative(root, file), shell: file.includes('/shell/') });
}
const esc = (v) => String(v ?? '').replace(/\|/g, '\\|');
const fmtDefault = (f) => f.default === undefined ? '—' : `\`${esc(JSON.stringify(f.default))}\``;
const fmtType = (f) => f.options ? `${f.type}: ${f.options.map((o) => `\`${o}\``).join(' · ')}`
  : f.min !== undefined ? `${f.type} ${f.min}–${f.max}` : f.type;

const section = (title, list) => [
  `## ${title}`, '',
  ...list.flatMap(({ s, file }) => [
    `### \`${s.type}\` — ${s.name}`, '', `Source: \`${file}\``, '',
    '| Setting | Type | Default | Notes |', '|---|---|---|---|',
    ...s.settings.map((f) => `| \`${f.id}\` | ${fmtType(f)} | ${fmtDefault(f)} | ${esc(f.label)} |`), '',
  ]),
];

const out = [
  '# Block reference', '',
  '> Generated by `npm run docs` from each block\'s `schema.js`. Do not edit by hand — change the schema and re-run.', '',
  'Every page (`src/content/pages/*.json`) and project (`src/content/projects/*.json`) is a list of `{ "type": "...", "settings": { ... } }`.',
  'Any content block also accepts `"anchor": "id"` to become a link target (e.g. `/#work`).', '',
  ...section('Content blocks', rows.filter((r) => !r.shell)),
  ...section('Shell blocks (used in site.json → header / footer)', rows.filter((r) => r.shell)),
].join('\n');
writeFileSync(join(root, 'docs/BLOCKS.md'), out + '\n');
console.log(`docs/BLOCKS.md — ${rows.length} blocks documented`);
